### ISSUE TITLE
No battery data dev 2.4.270

### ISSUE THREAD

**Issue by LeeFarm11** [britkat1980/ha-addons#2]
Hi Mark. I figured it would make more sense to create separate issue here in ha-addons rather than multiple issues within one Issue in the main givtcp area.

I have 6 batteries, but all of them show 0 data for voltage and temperature. This is in Dev 2.4.270
Is there anything I can give you to help?

![image](https://github.com/britkat1980/ha-addons/assets/169047365/8d23d2d7-5ef5-4fa8-a2fe-ba6883559d76)

I wonder if it relates to all these errors? -
`2024-05-31 06:14:07,519 - Inv1 - client      -  [CRITICAL] - Timeout awaiting 2:3/ReadHoldingRegistersResponse(slave_address=0x11 base_register=240) after 6 tries at 3s, giving up
2024-05-31 06:14:07,773 - Inv1 - client      -  [CRITICAL] - Timeout awaiting 2:3/ReadHoldingRegistersResponse(slave_address=0x11 base_register=300) after 6 tries at 3s, giving up
2024-05-31 06:14:08,024 - Inv1 - client      -  [CRITICAL] - Timeout awaiting 2:3/ReadHoldingRegistersResponse(slave_address=0x11 base_register=360) after 6 tries at 3s, giving up
2024-05-31 06:14:08,274 - Inv1 - client      -  [CRITICAL] - Timeout awaiting 2:3/ReadHoldingRegistersResponse(slave_address=0x11 base_register=1000) after 6 tries at 3s, giving up
2024-05-31 06:14:08,525 - Inv1 - client      -  [CRITICAL] - Timeout awaiting 2:3/ReadHoldingRegistersResponse(slave_address=0x11 base_register=1060) after 6 tries at 3s, giving up
2024-05-31 06:14:08,778 - Inv1 - client      -  [CRITICAL] - Timeout awaiting 2:3/ReadHoldingRegistersResponse(slave_address=0x11 base_register=1120) after 6 tries at 3s, giving up
2024-05-31 06:14:09,032 - Inv1 - client      -  [CRITICAL] - Timeout awaiting 2:4/ReadInputRegistersResponse(slave_address=0x70 base_register=60) after 6 tries at 3s, giving up
2024-05-31 06:14:09,283 - Inv1 - client      -  [CRITICAL] - Timeout awaiting 2:4/ReadInputRegistersResponse(slave_address=0x50 base_register=60) after 6 tries at 3s, giving up
2024-05-31 06:14:09,535 - Inv1 - client      -  [CRITICAL] - Timeout awaiting 2:4/ReadInputRegistersResponse(slave_address=0x51 base_register=60) after 6 tries at 3s, giving up
2024-05-31 06:14:09,786 - Inv1 - client      -  [CRITICAL] - Timeout awaiting 2:4/ReadInputRegistersResponse(slave_address=0x52 base_register=60) after 6 tries at 3s, giving up
2024-05-31 06:14:10,039 - Inv1 - client      -  [CRITICAL] - Timeout awaiting 2:4/ReadInputRegistersResponse(slave_address=0x53 base_register=60) after 6 tries at 3s, giving up
2024-05-31 06:14:10,289 - Inv1 - client      -  [CRITICAL] - Timeout awaiting 2:4/ReadInputRegistersResponse(slave_address=0x54 base_register=60) after 6 tries at 3s, giving up
2024-05-31 06:14:10,542 - Inv1 - client      -  [CRITICAL] - Timeout awaiting 2:4/ReadInputRegistersResponse(slave_address=0x55 base_register=60) after 6 tries at 3s, giving up
2024-05-31 06:15:03,743 - Inv1 - client      -  [CRITICAL] - Timeout awaiting 2:4/ReadInputRegistersResponse(slave_address=0x11 base_register=0) after 6 tries at 3s, giving up
2024-05-31 06:15:03,994 - Inv1 - client      -  [CRITICAL] - Timeout awaiting 2:4/ReadInputRegistersResponse(slave_address=0x11 base_register=180) after 6 tries at 3s, giving up
2024-05-31 06:15:04,248 - Inv1 - client      -  [CRITICAL] - Timeout awaiting 2:4/ReadInputRegistersResponse(slave_address=0x11 base_register=1000) after 6 tries at 3s, giving up
2024-05-31 06:15:04,497 - Inv1 - client      -  [CRITICAL] - Timeout awaiting 2:4/ReadInputRegistersResponse(slave_address=0x11 base_register=1060) after 6 tries at 3s, giving up
2024-05-31 06:15:04,751 - Inv1 - client      -  [CRITICAL] - Timeout awaiting 2:4/ReadInputRegistersResponse(slave_address=0x11 base_register=1120) after 6 tries at 3s, giving up
2024-05-31 06:15:05,003 - Inv1 - client      -  [CRITICAL] - Timeout awaiting 2:4/ReadInputRegistersResponse(slave_address=0x11 base_register=1180) after 6 tries at 3s, giving up
2024-05-31 06:15:05,256 - Inv1 - client      -  [CRITICAL] - Timeout awaiting 2:4/ReadInputRegistersResponse(slave_address=0x11 base_register=1240) after 6 tries at 3s, giving up
2024-05-31 06:15:05,505 - Inv1 - client      -  [CRITICAL] - Timeout awaiting 2:4/ReadInputRegistersResponse(slave_address=0x11 base_register=1300) after 6 tries at 3s, giving up
2024-05-31 06:15:05,759 - Inv1 - client      -  [CRITICAL] - Timeout awaiting 2:4/ReadInputRegistersResponse(slave_address=0x11 base_register=1360) after 6 tries at 3s, giving up
2024-05-31 06:15:06,013 - Inv1 - client      -  [CRITICAL] - Timeout awaiting 2:4/ReadInputRegistersResponse(slave_address=0x70 base_register=60) after 6 tries at 3s, giving up
2024-05-31 06:15:06,264 - Inv1 - client      -  [CRITICAL] - Timeout awaiting 2:4/ReadInputRegistersResponse(slave_address=0x50 base_register=60) after 6 tries at 3s, giving up
2024-05-31 06:15:06,516 - Inv1 - client      -  [CRITICAL] - Timeout awaiting 2:4/ReadInputRegistersResponse(slave_address=0x51 base_register=60) after 6 tries at 3s, giving up
2024-05-31 06:15:06,769 - Inv1 - client      -  [CRITICAL] - Timeout awaiting 2:4/ReadInputRegistersResponse(slave_address=0x52 base_register=60) after 6 tries at 3s, giving up
2024-05-31 06:15:07,020 - Inv1 - client      -  [CRITICAL] - Timeout awaiting 2:4/ReadInputRegistersResponse(slave_address=0x53 base_register=60) after 6 tries at 3s, giving up
2024-05-31 06:15:07,275 - Inv1 - client      -  [CRITICAL] - Timeout awaiting 2:4/ReadInputRegistersResponse(slave_address=0x54 base_register=60) after 6 tries at 3s, giving up
2024-05-31 06:15:07,526 - Inv1 - client      -  [CRITICAL] - Timeout awaiting 2:4/ReadInputRegistersResponse(slave_address=0x55 base_register=60) after 6 tries at 3s, giving up
2024-05-31 06:15:07,526 - Inv1 - read        -  [ERROR   ] - 5 consecutive timeout errors in watch loop. Restarting modbus connection:
2024-05-31 06:16:15,335 - Inv1 - client      -  [CRITICAL] - Timeout awaiting 2:4/ReadInputRegistersResponse(slave_address=0x11 base_register=0) after 6 tries at 3s, giving up
2024-05-31 06:16:15,587 - Inv1 - client      -  [CRITICAL] - Timeout awaiting 2:4/ReadInputRegistersResponse(slave_address=0x11 base_register=180) after 6 tries at 3s, giving up
2024-05-31 06:16:15,838 - Inv1 - client      -  [CRITICAL] - Timeout awaiting 2:4/ReadInputRegistersResponse(slave_address=0x11 base_register=1000) after 6 tries at 3s, giving up
2024-05-31 06:16:16,091 - Inv1 - client      -  [CRITICAL] - Timeout awaiting 2:4/ReadInputRegistersResponse(slave_address=0x11 base_register=1060) after 6 tries at 3s, giving up
2024-05-31 06:16:16,342 - Inv1 - client      -  [CRITICAL] - Timeout awaiting 2:4/ReadInputRegistersResponse(slave_address=0x11 base_register=1120) after 6 tries at 3s, giving up
2024-05-31 06:16:16,595 - Inv1 - client      -  [CRITICAL] - Timeout awaiting 2:4/ReadInputRegistersResponse(slave_address=0x11 base_register=1180) after 6 tries at 3s, giving up
2024-05-31 06:16:16,847 - Inv1 - client      -  [CRITICAL] - Timeout awaiting 2:4/ReadInputRegistersResponse(slave_address=0x11 base_register=1240) after 6 tries at 3s, giving up
2024-05-31 06:16:17,097 - Inv1 - client      -  [CRITICAL] - Timeout awaiting 2:4/ReadInputRegistersResponse(slave_address=0x11 base_register=1300) after 6 tries at 3s, giving up
2024-05-31 06:16:17,350 - Inv1 - client      -  [CRITICAL] - Timeout awaiting 2:4/ReadInputRegistersResponse(slave_address=0x11 base_register=1360) after 6 tries at 3s, giving up
2024-05-31 06:16:17,603 - Inv1 - client      -  [CRITICAL] - Timeout awaiting 2:3/ReadHoldingRegistersResponse(slave_address=0x11 base_register=0) after 6 tries at 3s, giving up
2024-05-31 06:16:17,855 - Inv1 - client      -  [CRITICAL] - Timeout awaiting 2:3/ReadHoldingRegistersResponse(slave_address=0x11 base_register=60) after 6 tries at 3s, giving up
2024-05-31 06:16:18,104 - Inv1 - client      -  [CRITICAL] - Timeout awaiting 2:3/ReadHoldingRegistersResponse(slave_address=0x11 base_register=120) after 6 tries at 3s, giving up
2024-05-31 06:16:18,358 - Inv1 - client      -  [CRITICAL] - Timeout awaiting 2:3/ReadHoldingRegistersResponse(slave_address=0x11 base_register=180) after 6 tries at 3s, giving up
2024-05-31 06:16:18,609 - Inv1 - client      -  [CRITICAL] - Timeout awaiting 2:3/ReadHoldingRegistersResponse(slave_address=0x11 base_register=240) after 6 tries at 3s, giving up
2024-05-31 06:16:18,861 - Inv1 - client      -  [CRITICAL] - Timeout awaiting 2:3/ReadHoldingRegistersResponse(slave_address=0x11 base_register=300) after 6 tries at 3s, giving up
2024-05-31 06:16:19,114 - Inv1 - client      -  [CRITICAL] - Timeout awaiting 2:3/ReadHoldingRegistersResponse(slave_address=0x11 base_register=360) after 6 tries at 3s, giving up
2024-05-31 06:16:19,368 - Inv1 - client      -  [CRITICAL] - Timeout awaiting 2:3/ReadHoldingRegistersResponse(slave_address=0x11 base_register=1000) after 6 tries at 3s, giving up
2024-05-31 06:16:19,619 - Inv1 - client      -  [CRITICAL] - Timeout awaiting 2:3/ReadHoldingRegistersResponse(slave_address=0x11 base_register=1060) after 6 tries at 3s, giving up
2024-05-31 06:16:19,869 - Inv1 - client      -  [CRITICAL] - Timeout awaiting 2:3/ReadHoldingRegistersResponse(slave_address=0x11 base_register=1120) after 6 tries at 3s, giving up
2024-05-31 06:16:20,120 - Inv1 - client      -  [CRITICAL] - Timeout awaiting 2:4/ReadInputRegistersResponse(slave_address=0x70 base_register=60) after 6 tries at 3s, giving up
2024-05-31 06:16:20,374 - Inv1 - client      -  [CRITICAL] - Timeout awaiting 2:4/ReadInputRegistersResponse(slave_address=0x50 base_register=60) after 6 tries at 3s, giving up
2024-05-31 06:16:20,626 - Inv1 - client      -  [CRITICAL] - Timeout awaiting 2:4/ReadInputRegistersResponse(slave_address=0x51 base_register=60) after 6 tries at 3s, giving up
2024-05-31 06:16:20,879 - Inv1 - client      -  [CRITICAL] - Timeout awaiting 2:4/ReadInputRegistersResponse(slave_address=0x52 base_register=60) after 6 tries at 3s, giving up
2024-05-31 06:16:21,132 - Inv1 - client      -  [CRITICAL] - Timeout awaiting 2:4/ReadInputRegistersResponse(slave_address=0x53 base_register=60) after 6 tries at 3s, giving up
2024-05-31 06:16:21,385 - Inv1 - client      -  [CRITICAL] - Timeout awaiting 2:4/ReadInputRegistersResponse(slave_address=0x54 base_register=60) after 6 tries at 3s, giving up
2024-05-31 06:16:21,640 - Inv1 - client      -  [CRITICAL] - Timeout awaiting 2:4/ReadInputRegistersResponse(slave_address=0x55 base_register=60) after 6 tries at 3s, giving up
2024-05-31 06:16:21,640 - Inv1 - read        -  [ERROR   ] - 5 consecutive timeout errors in watch loop. Restarting modbus connection:
2024-05-31 08:03:03,507 - Inv1 - client      -  [CRITICAL] - Timeout awaiting 2:4/ReadInputRegistersResponse(slave_address=0x11 base_register=180) after 6 tries at 3s, giving up
2024-05-31 08:03:05,770 - Inv1 - client      -  [CRITICAL] - Timeout awaiting 2:4/ReadInputRegistersResponse(slave_address=0x54 base_register=60) after 6 tries at 3s, giving up
2024-05-31 08:03:58,948 - Inv1 - client      -  [CRITICAL] - Timeout awaiting 2:4/ReadInputRegistersResponse(slave_address=0x11 base_register=0) after 6 tries at 3s, giving up
2024-05-31 08:03:59,201 - Inv1 - client      -  [CRITICAL] - Timeout awaiting 2:4/ReadInputRegistersResponse(slave_address=0x11 base_register=180) after 6 tries at 3s, giving up
2024-05-31 08:03:59,455 - Inv1 - client      -  [CRITICAL] - Timeout awaiting 2:4/ReadInputRegistersResponse(slave_address=0x11 base_register=1000) after 6 tries at 3s, giving up
2024-05-31 08:03:59,703 - Inv1 - client      -  [CRITICAL] - Timeout awaiting 2:4/ReadInputRegistersResponse(slave_address=0x11 base_register=1060) after 6 tries at 3s, giving up
2024-05-31 08:03:59,957 - Inv1 - client      -  [CRITICAL] - Timeout awaiting 2:4/ReadInputRegistersResponse(slave_address=0x11 base_register=1120) after 6 tries at 3s, giving up
2024-05-31 08:04:00,212 - Inv1 - client      -  [CRITICAL] - Timeout awaiting 2:4/ReadInputRegistersResponse(slave_address=0x11 base_register=1180) after 6 tries at 3s, giving up
2024-05-31 08:04:00,466 - Inv1 - client      -  [CRITICAL] - Timeout awaiting 2:4/ReadInputRegistersResponse(slave_address=0x11 base_register=1240) after 6 tries at 3s, giving up
2024-05-31 08:04:00,717 - Inv1 - client      -  [CRITICAL] - Timeout awaiting 2:4/ReadInputRegistersResponse(slave_address=0x11 base_register=1300) after 6 tries at 3s, giving up
2024-05-31 08:04:00,968 - Inv1 - client      -  [CRITICAL] - Timeout awaiting 2:4/ReadInputRegistersResponse(slave_address=0x11 base_register=1360) after 6 tries at 3s, giving up
2024-05-31 08:04:01,219 - Inv1 - client      -  [CRITICAL] - Timeout awaiting 2:4/ReadInputRegistersResponse(slave_address=0x70 base_register=60) after 6 tries at 3s, giving up
2024-05-31 08:04:01,470 - Inv1 - client      -  [CRITICAL] - Timeout awaiting 2:4/ReadInputRegistersResponse(slave_address=0x50 base_register=60) after 6 tries at 3s, giving up
2024-05-31 08:04:01,721 - Inv1 - client      -  [CRITICAL] - Timeout awaiting 2:4/ReadInputRegistersResponse(slave_address=0x51 base_register=60) after 6 tries at 3s, giving up
2024-05-31 08:04:01,975 - Inv1 - client      -  [CRITICAL] - Timeout awaiting 2:4/ReadInputRegistersResponse(slave_address=0x52 base_register=60) after 6 tries at 3s, giving up
2024-05-31 08:04:02,228 - Inv1 - client      -  [CRITICAL] - Timeout awaiting 2:4/ReadInputRegistersResponse(slave_address=0x53 base_register=60) after 6 tries at 3s, giving up
2024-05-31 08:04:02,479 - Inv1 - client      -  [CRITICAL] - Timeout awaiting 2:4/ReadInputRegistersResponse(slave_address=0x54 base_register=60) after 6 tries at 3s, giving up
2024-05-31 08:04:02,729 - Inv1 - client      -  [CRITICAL] - Timeout awaiting 2:4/ReadInputRegistersResponse(slave_address=0x55 base_register=60) after 6 tries at 3s, giving up
2024-05-31 08:05:08,569 - Inv1 - client      -  [CRITICAL] - Timeout awaiting 2:4/ReadInputRegistersResponse(slave_address=0x11 base_register=0) after 6 tries at 3s, giving up
2024-05-31 08:05:08,822 - Inv1 - client      -  [CRITICAL] - Timeout awaiting 2:4/ReadInputRegistersResponse(slave_address=0x11 base_register=180) after 6 tries at 3s, giving up
2024-05-31 08:05:09,075 - Inv1 - client      -  [CRITICAL] - Timeout awaiting 2:4/ReadInputRegistersResponse(slave_address=0x11 base_register=1000) after 6 tries at 3s, giving up
2024-05-31 08:05:09,327 - Inv1 - client      -  [CRITICAL] - Timeout awaiting 2:4/ReadInputRegistersResponse(slave_address=0x11 base_register=1060) after 6 tries at 3s, giving up
2024-05-31 08:05:09,577 - Inv1 - client      -  [CRITICAL] - Timeout awaiting 2:4/ReadInputRegistersResponse(slave_address=0x11 base_register=1120) after 6 tries at 3s, giving up
2024-05-31 08:05:09,831 - Inv1 - client      -  [CRITICAL] - Timeout awaiting 2:4/ReadInputRegistersResponse(slave_address=0x11 base_register=1180) after 6 tries at 3s, giving up
2024-05-31 08:05:10,083 - Inv1 - client      -  [CRITICAL] - Timeout awaiting 2:4/ReadInputRegistersResponse(slave_address=0x11 base_register=1240) after 6 tries at 3s, giving up
2024-05-31 08:05:10,335 - Inv1 - client      -  [CRITICAL] - Timeout awaiting 2:4/ReadInputRegistersResponse(slave_address=0x11 base_register=1300) after 6 tries at 3s, giving up
2024-05-31 08:05:10,588 - Inv1 - client      -  [CRITICAL] - Timeout awaiting 2:4/ReadInputRegistersResponse(slave_address=0x11 base_register=1360) after 6 tries at 3s, giving up
2024-05-31 08:05:10,841 - Inv1 - client      -  [CRITICAL] - Timeout awaiting 2:3/ReadHoldingRegistersResponse(slave_address=0x11 base_register=0) after 6 tries at 3s, giving up
2024-05-31 08:05:11,090 - Inv1 - client      -  [CRITICAL] - Timeout awaiting 2:3/ReadHoldingRegistersResponse(slave_address=0x11 base_register=60) after 6 tries at 3s, giving up
2024-05-31 08:05:11,345 - Inv1 - client      -  [CRITICAL] - Timeout awaiting 2:3/ReadHoldingRegistersResponse(slave_address=0x11 base_register=120) after 6 tries at 3s, giving up
2024-05-31 08:05:11,596 - Inv1 - client      -  [CRITICAL] - Timeout awaiting 2:3/ReadHoldingRegistersResponse(slave_address=0x11 base_register=180) after 6 tries at 3s, giving up
2024-05-31 08:05:11,849 - Inv1 - client      -  [CRITICAL] - Timeout awaiting 2:3/ReadHoldingRegistersResponse(slave_address=0x11 base_register=240) after 6 tries at 3s, giving up
2024-05-31 08:05:12,100 - Inv1 - client      -  [CRITICAL] - Timeout awaiting 2:3/ReadHoldingRegistersResponse(slave_address=0x11 base_register=300) after 6 tries at 3s, giving up
2024-05-31 08:05:12,354 - Inv1 - client      -  [CRITICAL] - Timeout awaiting 2:3/ReadHoldingRegistersResponse(slave_address=0x11 base_register=360) after 6 tries at 3s, giving up
2024-05-31 08:05:12,606 - Inv1 - client      -  [CRITICAL] - Timeout awaiting 2:3/ReadHoldingRegistersResponse(slave_address=0x11 base_register=1000) after 6 tries at 3s, giving up
2024-05-31 08:05:12,858 - Inv1 - client      -  [CRITICAL] - Timeout awaiting 2:3/ReadHoldingRegistersResponse(slave_address=0x11 base_register=1060) after 6 tries at 3s, giving up
2024-05-31 08:05:13,109 - Inv1 - client      -  [CRITICAL] - Timeout awaiting 2:3/ReadHoldingRegistersResponse(slave_address=0x11 base_register=1120) after 6 tries at 3s, giving up
2024-05-31 08:05:13,363 - Inv1 - client      -  [CRITICAL] - Timeout awaiting 2:4/ReadInputRegistersResponse(slave_address=0x70 base_register=60) after 6 tries at 3s, giving up
2024-05-31 08:05:13,612 - Inv1 - client      -  [CRITICAL] - Timeout awaiting 2:4/ReadInputRegistersResponse(slave_address=0x50 base_register=60) after 6 tries at 3s, giving up
2024-05-31 08:05:13,868 - Inv1 - client      -  [CRITICAL] - Timeout awaiting 2:4/ReadInputRegistersResponse(slave_address=0x51 base_register=60) after 6 tries at 3s, giving up
2024-05-31 08:05:14,117 - Inv1 - client      -  [CRITICAL] - Timeout awaiting 2:4/ReadInputRegistersResponse(slave_address=0x52 base_register=60) after 6 tries at 3s, giving up
2024-05-31 08:05:14,371 - Inv1 - client      -  [CRITICAL] - Timeout awaiting 2:4/ReadInputRegistersResponse(slave_address=0x53 base_register=60) after 6 tries at 3s, giving up
2024-05-31 08:05:14,623 - Inv1 - client      -  [CRITICAL] - Timeout awaiting 2:4/ReadInputRegistersResponse(slave_address=0x54 base_register=60) after 6 tries at 3s, giving up
2024-05-31 08:05:14,876 - Inv1 - client      -  [CRITICAL] - Timeout awaiting 2:4/ReadInputRegistersResponse(slave_address=0x55 base_register=60) after 6 tries at 3s, giving up`

**Comment by britkat1980** [comment]
fixed in dev version 2.4.272, can you test and see if it gets you all the right battery data and the correct serial numbers

**Comment by LeeFarm11** [comment]
Hi. I don't see so many error messages now, but still have all battery records showing 0C and 0V. Gap of an hour and a half in the logs at 18:23. Is that normal?

`Restarting modbus connection:
2024-06-01 18:21:19,835 - startup - [CRITICAL] - HA MQTT Service has been found at core-mosquitto
2024-06-01 18:21:19,838 - startup - [INFO] - Supervisor Timezone: Europe/London
2024-06-01 18:21:21,842 - startup - [INFO] - Searching for Inverters
2024-06-01 18:21:21,842 - startup - [CRITICAL] - Scanning network for GivEnergy Devices...
2024-06-01 18:22:11,609 - givenergy_modbus_async.client.client - [CRITICAL] - Timeout awaiting 2:4/ReadInputRegistersResponse(slave_address=0x04 base_register=60) after 11 tries at 3s, giving up
2024-06-01 18:22:11,858 - givenergy_modbus_async.client.client - [CRITICAL] - Timeout awaiting 2:4/ReadInputRegistersResponse(slave_address=0x05 base_register=60) after 11 tries at 3s, giving up
2024-06-01 18:22:12,110 - givenergy_modbus_async.client.client - [CRITICAL] - Timeout awaiting 2:4/ReadInputRegistersResponse(slave_address=0x06 base_register=60) after 11 tries at 3s, giving up
2024-06-01 18:22:12,361 - givenergy_modbus_async.client.client - [CRITICAL] - Timeout awaiting 2:4/ReadInputRegistersResponse(slave_address=0x07 base_register=60) after 11 tries at 3s, giving up
2024-06-01 18:22:12,612 - givenergy_modbus_async.client.client - [CRITICAL] - Timeout awaiting 2:4/ReadInputRegistersResponse(slave_address=0x08 base_register=60) after 11 tries at 3s, giving up
2024-06-01 18:22:12,613 - startup - [CRITICAL] - Inverter TDXXXXXXXX which is a Gen1 - Hybrid_3ph with 6 batteries has been found at: 192.168.1.108
2024-06-01 18:22:12,615 - startup - [CRITICAL] - Running Redis
2024-06-01 18:22:12,620 - startup - [CRITICAL] - Running Config Frontend
2024-06-01 18:22:12,621 - startup - [CRITICAL] - Setting up invertor: 1 of 1
2024-06-01 18:22:12,662 - startup - [CRITICAL] - Running RQ worker to queue and process givernergy-modbus calls
2024-06-01 18:22:12,663 - startup - [CRITICAL] - Running Invertor (192.168.1.108) read loop every 30/120s
2024-06-01 18:22:12,663 - startup - [CRITICAL] - Subscribing MQTT Broker for control
2024-06-01 18:22:12,665 - startup - [CRITICAL] - Starting Gunicorn on port 6345
[2024-06-01 18:22:13 +0100] [83] [INFO] Starting gunicorn 22.0.0
[2024-06-01 18:22:13 +0100] [83] [INFO] Listening at: http://0.0.0.0:6345 (83)
[2024-06-01 18:22:13 +0100] [83] [INFO] Using worker: sync
[2024-06-01 18:22:13 +0100] [85] [INFO] Booting worker with pid: 85
[2024-06-01 18:22:13 +0100] [86] [INFO] Booting worker with pid: 86
[2024-06-01 18:22:13 +0100] [87] [INFO] Booting worker with pid: 87
2024-06-01 18:22:14,235 - Inv1 - read        -  [INFO    ] - Starting watch_plant loop...
2024-06-01 18:22:14,253 - Inv1 - read        -  [CRITICAL] - Detecting inverter charateristics...
2024-06-01 18:22:14,312 - Inv1 - mqtt_client -  [CRITICAL] - Connecting to MQTT broker for control- core-mosquitto

> givtcp-vuejs@0.0.0 dev
> vite --host -l silent

2024-06-01 18:22:56,072 - Inv1 - client      -  [CRITICAL] - Timeout awaiting 2:4/ReadInputRegistersResponse(slave_address=0x04 base_register=60) after 11 tries at 3s, giving up
2024-06-01 18:22:56,320 - Inv1 - client      -  [CRITICAL] - Timeout awaiting 2:4/ReadInputRegistersResponse(slave_address=0x05 base_register=60) after 11 tries at 3s, giving up
2024-06-01 18:22:56,571 - Inv1 - client      -  [CRITICAL] - Timeout awaiting 2:4/ReadInputRegistersResponse(slave_address=0x06 base_register=60) after 11 tries at 3s, giving up
2024-06-01 18:22:56,822 - Inv1 - client      -  [CRITICAL] - Timeout awaiting 2:4/ReadInputRegistersResponse(slave_address=0x07 base_register=60) after 11 tries at 3s, giving up
2024-06-01 18:22:57,074 - Inv1 - client      -  [CRITICAL] - Timeout awaiting 2:4/ReadInputRegistersResponse(slave_address=0x08 base_register=60) after 11 tries at 3s, giving up
2024-06-01 18:23:05,559 - Inv1 - read        -  [INFO    ] - Publishing Home Assistant Discovery messages
2024-06-01 19:52:44,124 - Inv1 - client      -  [CRITICAL] - Timeout awaiting 2:4/ReadInputRegistersResponse(slave_address=0x11 base_register=1360) after 6 tries at 3s, giving up
2024-06-01 19:52:44,627 - Inv1 - client      -  [CRITICAL] - Timeout awaiting 2:3/ReadHoldingRegistersResponse(slave_address=0x11 base_register=60) after 6 tries at 3s, giving up
2024-06-01 19:52:46,395 - Inv1 - client      -  [CRITICAL] - Timeout awaiting 2:3/ReadHoldingRegistersResponse(slave_address=0x11 base_register=1060) after 6 tries at 3s, giving up
2024-06-01 19:52:46,645 - Inv1 - client      -  [CRITICAL] - Timeout awaiting 2:3/ReadHoldingRegistersResponse(slave_address=0x11 base_register=1120) after 6 tries at 3s, giving up
2024-06-01 19:53:34,686 - Inv1 - client      -  [CRITICAL] - Timeout awaiting 2:4/ReadInputRegistersResponse(slave_address=0x11 base_register=0) after 6 tries at 3s, giving up
2024-06-01 19:53:34,936 - Inv1 - client      -  [CRITICAL] - Timeout awaiting 2:4/ReadInputRegistersResponse(slave_address=0x11 base_register=180) after 6 tries at 3s, giving up
2024-06-01 19:53:35,188 - Inv1 - client      -  [CRITICAL] - Timeout awaiting 2:4/ReadInputRegistersResponse(slave_address=0x11 base_register=1000) after 6 tries at 3s, giving up
2024-06-01 19:53:35,438 - Inv1 - client      -  [CRITICAL] - Timeout awaiting 2:4/ReadInputRegistersResponse(slave_address=0x11 base_register=1060) after 6 tries at 3s, giving up
2024-06-01 19:53:35,690 - Inv1 - client      -  [CRITICAL] - Timeout awaiting 2:4/ReadInputRegistersResponse(slave_address=0x11 base_register=1120) after 6 tries at 3s, giving up
2024-06-01 19:53:35,941 - Inv1 - client      -  [CRITICAL] - Timeout awaiting 2:4/ReadInputRegistersResponse(slave_address=0x11 base_register=1180) after 6 tries at 3s, giving up
2024-06-01 19:53:36,193 - Inv1 - client      -  [CRITICAL] - Timeout awaiting 2:4/ReadInputRegistersResponse(slave_address=0x11 base_register=1240) after 6 tries at 3s, giving up
2024-06-01 19:53:36,443 - Inv1 - client      -  [CRITICAL] - Timeout awaiting 2:4/ReadInputRegistersResponse(slave_address=0x11 base_register=1300) after 6 tries at 3s, giving up
2024-06-01 19:53:36,694 - Inv1 - client      -  [CRITICAL] - Timeout awaiting 2:4/ReadInputRegistersResponse(slave_address=0x11 base_register=1360) after 6 tries at 3s, giving up
2024-06-01 19:54:24,719 - Inv1 - client      -  [CRITICAL] - Timeout awaiting 2:4/ReadInputRegistersResponse(slave_address=0x11 base_register=0) after 6 tries at 3s, giving up
2024-06-01 19:54:24,970 - Inv1 - client      -  [CRITICAL] - Timeout awaiting 2:4/ReadInputRegistersResponse(slave_address=0x11 base_register=180) after 6 tries at 3s, giving up
2024-06-01 19:54:25,222 - Inv1 - client      -  [CRITICAL] - Timeout awaiting 2:4/ReadInputRegistersResponse(slave_address=0x11 base_register=1000) after 6 tries at 3s, giving up
2024-06-01 19:54:25,474 - Inv1 - client      -  [CRITICAL] - Timeout awaiting 2:4/ReadInputRegistersResponse(slave_address=0x11 base_register=1060) after 6 tries at 3s, giving up
2024-06-01 19:54:25,724 - Inv1 - client      -  [CRITICAL] - Timeout awaiting 2:4/ReadInputRegistersResponse(slave_address=0x11 base_register=1120) after 6 tries at 3s, giving up
2024-06-01 19:54:25,975 - Inv1 - client      -  [CRITICAL] - Timeout awaiting 2:4/ReadInputRegistersResponse(slave_address=0x11 base_register=1180) after 6 tries at 3s, giving up
2024-06-01 19:54:26,226 - Inv1 - client      -  [CRITICAL] - Timeout awaiting 2:4/ReadInputRegistersResponse(slave_address=0x11 base_register=1240) after 6 tries at 3s, giving up
2024-06-01 19:54:26,479 - Inv1 - client      -  [CRITICAL] - Timeout awaiting 2:4/ReadInputRegistersResponse(slave_address=0x11 base_register=1300) after 6 tries at 3s, giving up
2024-06-01 19:54:26,729 - Inv1 - client      -  [CRITICAL] - Timeout awaiting 2:4/ReadInputRegistersResponse(slave_address=0x11 base_register=1360) after 6 tries at 3s, giving up`
